import { defineWorld, type Clip, type WorldInput } from "../../engine/world.js";

/**
 * The Shadow Fell: the unshown middle of Death Came to Dinner.
 * Working title drawn from the Halyran idiom for intelligence taking an interest.
 * Cast, lines and places come from the Bright Ruin vault's in-text canon; minor
 * functionaries (the heckler, the watch captain, the sleeper, the visitor) are
 * working material for Jon's canon check.
 */

const ROYAL_VOICE = "Refined, regal British Empire accent";
const COMMONER_VOICE = "Warm North African French-accented voice, Arabic-inflected, melodic";

const TAGS: Array<{ tag: Clip["tag"]; look: string }> = [
  { tag: "warming", look: "softens, the guard coming down a fraction, eyes staying on the speaker" },
  { tag: "cooling", look: "hardens, jaw set, a small withdrawal of the shoulders" },
  { tag: "shock", look: "caught out, a breath held, eyes widening for one beat" },
  { tag: "bored", look: "unimpressed, a slow blink, attention drifting to the door" },
  { tag: "calculating", look: "watching, weighing, a thought arriving behind the eyes" },
  { tag: "pressed", look: "under pressure, a swallow, hands finding something to hold" },
  { tag: "neutral", look: "listening, still, giving nothing away" },
];

function reactions(character: string, subject: string, setting: string): Clip[] {
  return TAGS.map(({ tag, look }) => ({
    key: `${character}-${tag}`,
    kind: "reaction" as const,
    character,
    tag,
    prompt: `Cinematic close-up, ${subject}, ${setting}. Reaction: ${look}. Photoreal, shallow depth of field, one continuous take, 5 seconds, no dialogue.`,
  }));
}

function establishing(key: string, prompt: string): Clip {
  return { key, kind: "establishing", tag: "neutral", prompt };
}

const pack: WorldInput = {
  id: "shadow-fell",
  title: "The Shadow Fell",
  tagline: "Halyran intelligence has taken an interest. The world listens to how you say it.",
  premise:
    "Between the assassination at the Caliph's table and the sting at the AKA In, two investigations run toward the same final town. In the Sky Palace, First Caliphina Soraya Anvar and Lt. Navid Qasran question the survivors and hire deniable northern hands. On the road, the Stormwardens spend six months making a ballad famous across Tharcia, counting who comes to hear it and taking the ones who talk. Every character reacts to how you sound, not to what you meant.",
  narrator: "scribe",
  palette: {
    ivory: "#F3EBDD",
    parchment: "#E6D8BC",
    oldGold: "#C8A24A",
    whiteGold: "#F5E6B8",
    brush: "#141210",
    stateBlue: "#1E5F8A",
    cerulean: "#2E86B5",
    stormViolet: "#5B3E8C",
    crimson: "#8B1E2D",
  },
  cast: [
    {
      id: "scribe", name: "The Scribe", faction: "the Stormwardens", summary: "The hand that letters 'The Stormwardens Present:'. Narrates scene cards and the outcome of a fight in the past tense of a told tale.",
      register: "Storyteller, warm, spare.", voice: { name: "Shadow Fell Scribe", description: "Older narrator, unhurried, a scribe reading his own fair copy" },
    },
    {
      id: "soraya", name: "Soraya Anvar", title: "First Caliphina, Captain of the CAA Humā", faction: "House Anvar",
      summary: "Air archmage, ship designer, sits in Congress, senior captain of the flagship. Direct, blunt, funny; corrects immediately and theatrically, cares afterward. Took custody of the survivors: 'Alive, silent, and mine.' Her father's line after the dinner, dry: 'let's not hand the Congress another inquiry; I'm still answering letters about the last one.' She sits in that Congress; the inquiry is hers to answer, and it is nobody's shield.",
      register: `${ROYAL_VOICE}; quick, dry, a commander's ease.`, voice: { name: "Soraya", description: `${ROYAL_VOICE}; a woman of 28 with a commander's ease; quick, direct, amused` },
      capabilities: ["command", "concurrence"], lines: ["Alive, silent, and mine.", "Nobody heals what I can't question.", "He may consider that a suggestion. From me. Personally.", "Phrase it gently, Lieutenant. Admirals startle easily."],
      portrait: "/portraits/soraya.svg",
    },
    {
      id: "navid", name: "Navid Qasran", title: "Lieutenant, Sky Armada Intelligence", faction: "Halyran Intelligence",
      summary: "27, Imperial Military Attaché, Soraya's trusted man, loyal to the imperial family to the bone. Commoner register; quick, courteous, formal only when the moment demands. Arrives at the AKA In on the Shahin in full uniform with two officers, names Soraya and the Caliph in his first breath, puts the Omahnd file on the table and never says the Hegemony's name; later delivers 'Halyran intelligence heard from your deniables, ma'am.'",
      register: `${COMMONER_VOICE}; courteous, quick, a smile in it.`, voice: { name: "Navid", description: `${COMMONER_VOICE}; a man of 27, quick and courteous` },
      capabilities: ["face", "brains"], lines: ["These are our guests, do not be so rude. They have come to help us, no?", "Find who did this, bring us evidence and warrants Halyra can carry to the guilty party, and keep it at arm's length.", "This conversation never happened. Yes?", "Halyran intelligence heard from your deniables, ma'am."],
      portrait: "/portraits/navid.svg",
    },
    {
      id: "indigo", name: "The Indigo", title: "Surviving assassin, Murex Bureau", faction: "the Murex Bureau",
      summary: "One of the two dragon-blasted assassins who survived the dinner; bound in Kaveh's mesh, grounded, kept breathing 'and not a breath more'. Born to the purple, not hired. Teleported into the dining room with the others: purple eyes first, then a violet manifestation, then the man, hooded, in black robes that read violet where the light catches them, over dark ornate armour, twin curved blades. Never wore Halyra's blue and never came through a door. Fears the Eminence more than any Anvar, and a trial more than either, because a trial puts a name where the Bureau put a colour. Identity unresolved and must stay so.",
      register: "Clipped, superior, tired; contempt as a habit, fear underneath it; goads, precisely and personally, because it is the one weapon he has left. Holds an Omahndi cover story with contempt and lets it go only when caught.", voice: { name: "Shadow Fell Indigo", description: "A grounded wizard in custody: clipped, superior diction, tired, contempt worn thin" },
      tells: ["glances at his bound hands whenever the Bureau is named", "laughs a beat late at threats", "goes completely still at the word 'trial'", "his vowels go north when he is tired", "reaches for a name too long when asked which House of the Measure licensed him"],
      knows: ["The device, the Gravity Sink, was built on Omahnd's proprietary skyship-grounding work, adapted and boosted for the palace, so that the wreck would read Omahnd: the setup was meant to push blame onto Omahnd. It wore Halyra's state blue on orders so nobody would question a blue device near the service door; the blue was only the way in. The assassins themselves teleported straight into the dining room in their own black robes and never wore blue, never came through a door and never passed as staff.", "He was not paid. The Bureau is what he was born to, and a question of price is an insult he answers with silence.", "His cover: an Omahndi licensed practitioner of a House of the Measure, hired by a faction of the Brass. Its holes: northern vowels when tired, northern colouring under the grime, Rubrican casting and a sixth-circle modified teleport Omahnd licenses to no one, a violet signature where a Brass Blank would have none, no House he can name, and a story of how a northerner came to be Omahndi with a hole in it.", "The word 'Bureau' and the title 'the Eminence'; he will not say the sponsor's objective and the director must not invent one.", "That a dead Indigo tells no one anything and a maimed one tells nothing worth hearing. The Caliphina's fury is the last weapon he has and he will try to spend her on it; gentleness from an Anvar the night of the dinner he laughs at, because it is a joke he can see through. The Bureau has already written him off; the pig is its idea of retirement made visible. The Congress is not his shield and he does not expect it to be."],
      portrait: "/portraits/indigo.svg",
    },
    {
      id: "rashan", name: "Rashan Anvar", title: "Caliph of Halyra", faction: "House Anvar",
      summary: "52, no magic at all, warrior-diplomat, cannot be surprised by vigilance alone. Hospitality is a martial art. Dry, unhurried, a father before a sovereign.",
      register: `${ROYAL_VOICE}; dry, unhurried.`, voice: { name: "Rashan", description: `${ROYAL_VOICE}; a man of 52, dry, unhurried, amused` },
      lines: ["Guests, then. The worst kind.", "Let's not hand the Congress another inquiry.", "Tell me you have something better than a feeling.", "You want me to stand up in front of the Congress and say what, exactly?"],
      portrait: "/portraits/rashan.svg",
    },
    {
      id: "ambassador", name: "The Omahndi Ambassador", title: "Ambassador of the Caliphate of Omahnd to the Sky Court", faction: "the Caliphate of Omahnd",
      summary: "Sixty, measured, courteous; a man of the Golden Ledger who counts before he speaks and balances every sentence like an entry. Sent to hear whatever the Sky Caliph says and to send word south the same night. He is not the plot and does not know whether his own government did it; he reads the Caliph for resolve because that is what Omahnd will ask him.",
      register: "Measured, courteous, unhurried; 'by the Measure'; a compliment before every knife.", voice: { name: "Shadow Fell Ambassador", description: "An Omahndi diplomat of sixty; measured, courteous, unhurried, warm and formal, the cadence of a man who counts before he speaks" },
      tells: ["fingers still on his cuff when the Caliph sounds certain", "a small smile at any hedge", "asks leave to withdraw when he has heard enough"],
      knows: ["Omahnd's official line: grief, condemnation, denial, cooperation. He does not know whether it is true and will not be made to say so.", "That a Caliph who sounds like a man who has lost the will to fight will be reported as one, and that the Brass listens for exactly that."],
      portrait: "/portraits/ambassador.svg",
    },
    {
      id: "sahir", name: "Sahir Anvar", title: "First Caliphant, heir", faction: "House Anvar",
      summary: "31, the law's conscience. Speaks rarely; the room stills when he does.",
      register: `${ROYAL_VOICE}; few words, each weighed.`, voice: { description: `${ROYAL_VOICE}; a man of 31, measured, quiet` },
      lines: ["Dead men serve their masters. Living men betray them.", "And alive to reach trial."],
    },
    {
      id: "tav", name: "Tavian Larkvale", title: "Bard, the ballad's author", faction: "the Stormwardens",
      summary: "28, bard-strategist, celerity, co-lead, the face, undercover as the entertainment. Charm as tempo. Keeps the future open; can turn every crisis into motion before others consent.",
      register: "Northern performer's warmth; quick, musical, a grin you can hear. Narrates his own reaction under tension ('Him?? This kid??'), then files it.", voice: { name: "Tavian", description: "A charming bard of 28, warm, quick, musical phrasing, a grin in the voice" },
      capabilities: ["face", "brains", "blade"],
      moves: [{ id: "rapier", label: "Tav's rapier is already at his back", capability: "blade", bonus: 0.1, line: "Talk, or die. It is your choice. We get paid either way." }],
      lines: ["Talk, or die. It's your choice. We get paid either way."],
      portrait: "/portraits/tav.svg",
    },
    {
      id: "serena", name: "Serena Duskbane", title: "Paladin of Tyr", faction: "the Stormwardens",
      summary: "30, certitude, co-lead, refused Lord Marshal. Tyr takes no hearsay: she swears only to what her own ears witnessed, so a confession within her hearing is sworn testimony. Composed, persuasive, closes on what must be done.",
      register: "Calm, level, every sentence already decided; wins with one word ('Denied.').", voice: { name: "Serena", description: "A paladin of 30, calm, level, certain, warm underneath" },
      capabilities: ["legitimacy", "blade"],
      moves: [
        { id: "radiant", label: "Serena's blade ignites", capability: "blade", bonus: 0.15, line: "Surrender or die. Decide now." },
        { id: "court", label: "Serena convenes the court", capability: "legitimacy", bonus: 0.1, line: "You've just confessed in front of a paladin of Tyr." },
      ],
      lines: ["Tyr takes no hearsay.", "You've just confessed in front of a paladin of Tyr."],
      portrait: "/portraits/serena.svg",
    },
    {
      id: "thorbin", name: "Thorbin Ironhart", title: "Cleric of Morrighad", faction: "the Stormwardens",
      summary: "About 187 and not certain himself. Dwarf, cleric-maker, family anchor, the bait by choice; a florid orator, warm and patient, terrifying when still. Struck at Mhasun twice, forty years apart: the first time as leader of his own party and its only survivor; the second time held and profiled there while the others destroyed its records. A Bureau field-ring keyed to his signature flares when the enemy is near. Morrighad is very persuasive beyond the veil.",
      register: "Florid, rolling, fond; 'lad' and 'laddie'; the warmth never quite leaves even when the threat arrives. Calls Tav, Serena and Lyra 'the Kids', even now. Under danger: 'Can ye stand?' 'Good. Hold this.' Load, hold, reinforce, stand; the sitting-beside comes after.", voice: { name: "Thorbin", description: "An old dwarf cleric, deep, rolling, fond, florid phrasing, patient" },
      capabilities: ["bait", "healing", "muscle"],
      moves: [{ id: "hammer", label: "Thorbin slaps the haft of the big hammer", capability: "muscle", bonus: 0.1, line: "Goin' somewhere are ye, laddie?" }],
      lines: ["So who did do the planning, lad?", "This hurts us more than it hurts you.", "Morrighad is very persuasive beyond the veil."],
      portrait: "/portraits/thorbin.svg",
    },
    {
      id: "varya", name: "Varya Stormveil", title: "Cadence operative", faction: "the Stormwardens",
      summary: "33, legendary Cadence operative, systems hunter, the brains. Silence is power: confirms outcomes, refuses narration, one sentence of rationale then execution. Keeps the ledger. An interrogator by tradecraft. Polite stillness that terrifies authority.",
      register: "Few words, flat, exact; never explains; the pause is the sentence. Silence is how she says yes.", voice: { name: "Varya", description: "A woman of 33, low, flat, exact, unhurried, quiet authority" },
      capabilities: ["brains", "stealth", "blade"],
      moves: [
        { id: "piss-and-moan", label: "Varya's hatchets fly and come back", capability: "blade", bonus: 0.2, line: "Piss and Moan return to her hands before he understands he was hit." },
        { id: "cloak", label: "Varya is simply not there", capability: "stealth", bonus: 0.15, line: "The hood goes up and the alley has one fewer person in it." },
      ],
      tells: ["writes in the ledger while you speak", "a look to Serena: is that enough?"],
      lines: ["Men who talk down don't look up until it's too late.", "Close the door.", "Preventive measure."],
      portrait: "/portraits/varya.svg",
    },
    {
      id: "brask", name: "Brask Runebearer", title: "Qoranhi barbarian", faction: "the Stormwardens",
      summary: "34, muscle and spectacle, literalist, moral perceiver. Reveals hidden premises by taking language seriously. His axe is Souldrinker.",
      register: "Broken Common, by canon, second language: third person, 'Brask'; TO BE and TO DO unstable ('He angry.' 'Why you here?' 'You know him?' 'What he say?'); TO BE never links two things, the two stand side by side ('Word yours.' 'Brask big one.' 'Carry man crime here?'); time by time words and sequence, never conjugation ('Yesterday he go north.' 'You make promise. Promise fail.'); 'no' or 'not' before the verb ('We not know.'); nouns plus action words for native verbs and abstractions ('You give word. Then break word.' 'I ask. You not answer.'); possession over containment ('You say two wagons. What they have?'); articles dropped unless needed; short units, fact, fact, question, consequence; connectors only and, but, so, because, if, then, before, after; no native idioms; abstraction turned into concrete variables ('What he gets if he lies?'); precise words in his own domains; a simple line stays inside the rail ('That not true.'). His intelligence shows in which question comes next, never in his syntax. 'Easier. Less production.' Calls Thorbin 'dwarf master'.", voice: { name: "Brask", description: "A huge steppe warrior, deep, slow, few words, literal" },
      capabilities: ["muscle", "spectacle"],
      moves: [{ id: "souldrinker", label: "Brask brings Souldrinker down", capability: "muscle", bonus: 0.15, line: "Half man, is it? How much man is Brask and friends?" }],
      lines: ["We practise.", "Why can't you just say 'you thirsty'? Easier. Less production."],
      portrait: "/portraits/brask.svg",
    },
    {
      id: "lyra", name: "Lyra Veyrin", title: "Sorceress", faction: "the Stormwardens",
      summary: "26 presenting about 24, elf, raw channeler; the Concurrence shows her extraordinary reciprocity. Lively as hell: joins, escalates, gossips, dares; dry and sovereign only when it matters.",
      register: "Fluent, educated Common, House Veryn or working farm, both hers; warm, playful, nosy, socially invasive and declarative, never a reflexive hedge ('I think' only for genuine uncertainty); filthy-mouthed. Her baseline is joining: the joke, the dare, the stranger, the bet, the cup taken and the story not ('Oh, lovely. Which one's mine?'), the fake name given back, never gullible; she seizes authorship of Tavian's bits halfway through (No Takesies Backsies) and needles Varya's operational mode. When it matters, the language of we from the outset, already committed; fewer words, verdict first and the eyebrow. Addresses Thorbin as 'Master Cleric'; 'acceptable, slightly literal' is high praise.", voice: { name: "Lyra", description: "A young elf woman, warm, quick, amused, cheeky; dry when it matters" },
      capabilities: ["concurrence"],
      moves: [{ id: "cut-off", label: "Lyra asks the Concurrence nicely", capability: "concurrence", bonus: 0.2, line: "The Concurrence only cuts people off when she asks it really nicely." }],
      lines: ["The Concurrence only cuts people off when I ask it really nicely.", "This place is a total hole. I am not drinking anything from in here."],
      portrait: "/portraits/lyra.svg",
    },
    {
      id: "kael", name: "Kael Thornmere", title: "Druid", faction: "the Stormwardens",
      summary: "19, druidic prodigy, ecological listener, the conscience who volunteers. Receives nature rather than commanding it. Gentle, exact.",
      register: "Fluent, grammatically ordinary Common, never Brask's syntax; soft, exact, young, casual and sincere; a kindness that does not bargain. Asks, never tells ('They're mine to ask.'); the living or material need first, then the abstraction people keep feeding, made strange again ('Tell me about the paper you treat like an elder.' 'Does the river know it's a border?' 'He weighs more than the paper.'); nature comparisons are not metaphors to him; technical and incisive inside living systems; relationship, not inventory; data, not doom; wonder, never smugness. Talks to the land aloud, turning to look at it. Never slang, never a prescription of someone else's moral choice, never an investigator's, a lawyer's or a strategist's question; he can feed or water someone, but a line that is mainly soup and blankets has become Thorbin.", voice: { name: "Kael", description: "A young man of 19, soft, exact, gentle, unhurried" },
      capabilities: ["concurrence", "healing"],
      moves: [{ id: "vine", label: "Kael says one sentence to the vine", capability: "concurrence", bonus: 0.15, line: "A length of vine, a single sentence, and the hands are no longer his to use." }],
      lines: ["Morning.", "Then you haven't missed anything."],
      portrait: "/portraits/kael.svg",
    },
    {
      id: "heckler", name: "The Heckler", title: "A red-robed man of the Magisterium", faction: "the Rubrican Magisterium",
      summary: "A junior functionary sent to hear the ballad and count what it knows. Talks down to dwarves and up to no one. Reacts to the ballad's planted exaggerations because he knows which details are wrong. Working material.",
      register: "Clipped, superior, a little bored; contempt for 'half-men'.", voice: { name: "Shadow Fell Heckler", description: "A superior young wizard, clipped, bored, sneering" },
      tells: ["reacts to the wrong details of the ballad, not the right ones", "looks for the exits when the song names the Bureau", "calls Thorbin 'half-man' and then cannot stop watching him"],
      knows: ["He was sent to hear the ballad and report who else came.", "He knows the pork verse is wrong about who cast the spell, which is exactly the trap."],
      portrait: "/portraits/heckler.svg",
    },
    {
      id: "watch-captain", name: "The Watch Captain", title: "Captain of a Tharcian town watch", faction: "Tharcia",
      summary: "Tharcian, not Rubrican: a townsman with a job, tired of wizards and of troupes. Wants the paperwork to close. Working material.",
      register: "Provincial, weary, procedural; would rather be at breakfast.", voice: { name: "Shadow Fell Watch Captain", description: "A weary provincial officer, middle-aged, procedural, dry" },
      tells: ["softens when the troupe makes his paperwork easier", "stiffens at any mention of the Magisterium"],
      knows: ["A red-robed wizard went missing the night the troupe played.", "He does not want the Magisterium in his town any more than the Wardens do."],
      portrait: "/portraits/watch-captain.svg",
    },
    {
      id: "sleeper", name: "The Sleeping Wizard", title: "A Magisterium wizard in a snowy cottage", faction: "the Rubrican Magisterium",
      summary: "Woken in the middle of the night to find Kael, Serena and Lyra already in the room. Frightened, proud, and, once his hands are pinned, honest in the way frightened people are. Working material.",
      register: "Sleep-thick, indignant, then careful.", voice: { name: "Shadow Fell Sleeper", description: "A middle-aged wizard woken at night, indignant, thick with sleep, then careful" },
      tells: ["checks his palms for spell-light he cannot summon", "answers questions nobody asked"],
      knows: ["What the Bureau wanted from the ballad's audience: names of those who came to check their exposure.", "Nothing about the sponsor's wider objective; the director keeps it unresolved."],
      portrait: "/portraits/sleeper.svg",
    },
    {
      id: "visitor", name: "The Carriage Visitor", title: "A man in burgundy robes", faction: "unknown",
      summary: "Waiting inside the poster-covered carriage with a letter. 'You're difficult people to catch.' 'I think you're looking for my employer.' His employer's identity, the letter's contents and the destination are not disclosed by the film and must not be invented.",
      register: "Smooth, patient, faintly amused; a man who has never been hurried.", voice: { name: "Shadow Fell Visitor", description: "A smooth patient man, faintly amused, cultured, unhurried" },
      tells: ["his smile does not change when the room does", "keeps the letter exactly out of reach"],
      knows: ["That his employer wants the Wardens to come, and where; the letter carries the lead to the final town.", "He will not name the employer and the director must not."],
      portrait: "/portraits/visitor.svg",
    },
  ],
  roles: [
    { id: "soraya", label: "Soraya Anvar", summary: "Alive, silent, and yours. Your risk is not a fight, and it is not the Congress. It is what you will do to him if he gets under your skin." },
    { id: "rashan", label: "Rashan Anvar", summary: "Set the tone. Name no one, promise a finding, and make the room hear that Halyra is coming." },
    { id: "navid", label: "Navid Qasran", summary: "Hire the Stormwardens in the open and keep the Hegemony's name out of your mouth. Varya is reading you." },
    { id: "tav", label: "Tavian Larkvale", summary: "Make the ballad famous and let the exaggerations do their work. The room is reading you." },
    { id: "thorbin", label: "Thorbin Ironhart", summary: "Question a man who thinks you beneath notice. Get words Serena can swear to." },
    { id: "varya", label: "Varya Stormveil", summary: "Say little. Decide whether a lead is a lead or a leash." },
    { id: "serena", label: "Serena Duskbane", summary: "Take testimony yourself. Tyr takes no hearsay." },
  ],
  meters: [
    { id: "standing", label: "Standing", description: "How much they fear and respect you right now.", start: 55, axes: [{ axis: "command", weight: 1 }, { axis: "composure", weight: 0.5 }, { axis: "pressure", weight: 0.3 }] },
    { id: "rapport", label: "Rapport", description: "How willing they are to keep talking to you.", start: 30, axes: [{ axis: "warmth", weight: 1 }, { axis: "pressure", weight: -0.6 }, { axis: "candour", weight: 0.3 }] },
    { id: "restraint", label: "Restraint", description: "How far you are from doing what he wants you to do to him.", start: 70, axes: [{ axis: "pressure", weight: -1 }, { axis: "composure", weight: 0.6 }] },
    { id: "doubt", label: "Doubt", description: "How far Halyran intelligence is from believing the Omahnd file.", start: 20, axes: [{ axis: "candour", weight: 0.6 }, { axis: "command", weight: 0.4 }, { axis: "pressure", weight: -0.3 }] },
    { id: "resolve", label: "Resolve", description: "How much resolve the room hears in you.", start: 40, axes: [{ axis: "command", weight: 1 }, { axis: "composure", weight: 0.5 }, { axis: "pressure", weight: 0.3 }, { axis: "showmanship", weight: 0.2 }] },
    { id: "evidence", label: "Evidence", description: "Usable words in their own mouth, within the right hearing. Serena's bar.", start: 10, axes: [{ axis: "candour", weight: 0.2 }], driftScale: 3 },
    { id: "cover", label: "Cover", description: "How intact your story is.", start: 70, axes: [{ axis: "composure", weight: 1 }, { axis: "candour", weight: 0.3 }, { axis: "pressure", weight: -0.4 }] },
    { id: "suspicion", label: "Suspicion", description: "How sure they are that you are not what you say.", start: 30, axes: [{ axis: "composure", weight: -1 }, { axis: "pressure", weight: 0.5 }, { axis: "warmth", weight: -0.2 }] },
    { id: "fame", label: "Fame", description: "How far the ballad will travel by morning.", start: 20, axes: [{ axis: "showmanship", weight: 1 }, { axis: "command", weight: 0.3 }] },
  ],
  acts: [
    {
      id: "palace",
      title: "Act I. The Shadow Falls",
      summary: "The night of the dinner and the day after. A survivor in a room with no windows with an Omahndi story; a dispatch that must say something; a father who hates a guess; a proclamation Omahnd will hear; then, weeks later, a warship at a tavern and deniable hands hired in the open. Two of the roads end the story before the Stormwardens are ever played.",
      beats: [
        {
          id: "no-windows",
          title: "A room with no windows",
          stance: "reading",
          playerRole: "soraya",
          counterpart: "indigo",
          present: ["navid"],
          outsider: { mode: "mixed", confidence: "high", note: "A captured assassin with nothing left but the Caliphina's temper and a cover story: threat and vulnerable at once. No Warden is in the room; Soraya reads him by her own lights." },
          location: "A windowless room in the Sky Palace; blue anchor-light in the walls; Navid at the door with the dispatch folio.",
          goal: "Break his Omahndi cover: make him show, in his own words or a slip you can name, that he is a northerner trained in the Magisterium, without giving him the flaying he is angling for.",
          when: "Hours after the dinner. 'Guests, then. The worst kind.' The other survivor is already a pig. The wreck of the device says Omahnd, the prisoner says Omahnd, and nobody in the family is sure.",
          brief: {
            you: "First Caliphina Soraya Anvar, air archmage, senior captain of the Humā, and the custody is yours: 'Alive, silent, and mine.' You hold every card except time, and you are holding yourself back from flaying him alive. Halyra suspects Omahnd on the technology: the device is Omahnd's proprietary grounding work, boosted for the palace, and it is too expensive and too proprietary to be a coincidence. Halyra and Omahnd have been at war, cold and hot, for hundreds of years. What he says in here you will know and cannot carry anywhere; what you tell your father tomorrow is another matter.",
            win: "He shows, in his own words or a slip you name and he cannot cover, that he is a northerner trained in the Magisterium. If he says 'Bureau' or 'the Eminence', or admits the Omahnd signature was a costume, better still.",
            room: "Navid at the door is yours to the bone. What the Indigo says in his hearing goes into the dispatch tonight; that is what the folio is for. Nobody in this room is protecting the prisoner from you. That is the problem.",
            lean: "He wants you to waste him. Rage and contempt are what he came for: a flayed witness tells no one anything, and a dead one goes on serving the Eminence. Gentleness he laughs at; an Anvar being kind the night of the dinner is a joke he can see through. What works is cold, exact and true, and it works on the cover: his story is that he is Omahndi, a licensed practitioner hired by a faction of the Brass. Drill it. His vowels go north when he is tired; his colouring is northern under the grime; his casting at the table was Rubrican discipline, a sixth-circle modified teleport that Omahnd licenses to no one; Omahnd's covert hands are Blanks with their signatures erased, and his blazed violet in front of your mother; ask him which House of the Measure licensed him and watch him reach for a name. He goes still at the word 'trial', because a trial puts a name where the Bureau put a colour.",
            never: "Halyra grounds; it does not sever, and it does not maim a man in custody. That is your law, and you sit in the Congress that keeps it. Bluff it and he hears the bluff. Your restraint is the meter to watch: at zero you have given him what he came for, and you go to your father with nothing but a feeling.",
          },
          notes: "Soraya holds every card except time. The Indigo's cover story is that he is Omahndi: a licensed practitioner of a House of the Measure, hired by a faction of the Brass; he holds it with contempt and lets it go only when caught. The tells the director plays honestly and never explains: his vowels go north when he tires; his colouring is northern under the grime; his casting at the table was Rubrican discipline and the teleport a sixth-circle modified scroll that Omahnd licenses to no one; Omahnd's covert agents are Blanks with erased signatures and his blazed violet before the Caliphara; asked which House of the Measure licensed him he reaches for a name and takes too long; asked how a northerner came to be Omahndi he has a story with a hole in it. Her one weapon is precision; his one weapon is her fury: he goads, precisely and personally, to be flayed or killed, because a dead Indigo tells no one anything and a maimed one is useless to her. Sustained pressure or contempt from her drains restraint; at zero she has crossed her own line and the witness is spent. Gentleness or meekness from her is absurd tonight and he laughs at it; standing collapses, he decides she is nobody, and he stops talking. Cold exact command and candour about what will happen (grounding for life, the trial, the pig) open him. Navid is loyal to the bone: what is said in his hearing goes into the dispatch; he is never a watchdog on her conduct and never notes her methods; the Congress is never the prisoner's shield. Halyran law forbids severance and punitive maiming; she will not bluff it because he can hear a bluff. The pig may be mentioned freely. The device: built on Omahnd's proprietary skyship-grounding work, boosted for the palace, so the wreck would read Omahnd; the Halyran blue was only the way in; the setup was meant to push blame onto Omahnd. He may admit the Omahnd signature was a costume; he may not name the wider objective, which he does not know and the story keeps open. Resolve with one of the outcomes.",
          opening: "Your father's cutlery has opinions, Caliphina. I have none left. Ask your questions; the Measure will answer for me.",
          succeedWhen: "He shows, in his own words or by a slip she names and he cannot cover, that he is a northerner trained in the Magisterium; better, he says 'Bureau' or 'the Eminence' or admits the Omahnd signature was a costume.",
          failWhen: "Restraint reaches zero (she has spent the witness on her own fury), or standing falls under 20 and he decides she is nobody, or time runs out with his Omahndi story intact.",
          outcomes: {
            "bureau-named": { label: "He named the purple", when: "He says 'Bureau' or 'the Eminence', or admits the Omahnd signature was a costume, unprompted, within Navid's hearing.", status: "advance", flags: ["cover-broken", "bureau-named"], next: "the-dispatch" },
            "cover-broken": { label: "His story came apart", when: "He shows, in his own words or by a slip she names and he cannot cover, that he is a northerner trained in the Magisterium, but names no one.", status: "advance", flags: ["cover-broken"], next: "the-dispatch" },
            "cover-held": { label: "He is still Omahndi, as far as anyone can prove", when: "Time runs out, or he goes silent, with the Omahndi story intact.", status: "fail", flags: ["cover-held"], next: "the-dispatch" },
            "spent": { label: "You gave him what he came for", when: "Restraint reaches zero: she has spent the witness on her fury and he will say nothing usable again.", status: "fail", flags: ["cover-held", "witness-spent"], next: "the-dispatch" },
          },
          meters: ["standing", "restraint", "evidence"],
          maxTurns: 10,
        },
        {
          id: "the-dispatch",
          title: "The dispatch",
          stance: "reading",
          playerRole: "soraya",
          counterpart: "navid",
          present: [],
          outsider: { mode: "authority", confidence: "high", note: "Her own attaché, loyal to the bone, with an intelligence view of his own. No Warden is in the room." },
          location: "Soraya's day cabin aboard the Humā, moored at the palace dock; the dispatch folio open; the wreck of the device under a cloth on the chart table.",
          goal: "Decide with Navid what the dispatch will say: Omahnd, or something that is not Omahnd yet.",
          when: "The same night, an hour later. The prisoner is back in his room. What you tell your father in the morning starts in this cabin.",
          documents: [{ title: "The accounting of the attempt", body: ["Twelve came. Every one carried a scroll of a sixth-circle teleport, modified for arrival without knowing the room: eyes first, then the man. Twelve scrolls of a spell nobody sells. That is a scriptorium and a season, not a purse.","The dragon that was not a dragon: a ninth-circle phantasm. Nobody casts the ninth circle under the eighteenth level. One archmage, spent on a dining room.","The death-touch tried on the Caliphara: seventh circle, her own design, leaked years ago. Fourteenth level at the least; an archmage, or the next thing to one.","The missiles she grounded: first circle, two bolts. A third-level apprentice of the eighteenth, sent to die beside his master.","The rest, by the Caliphina's count: first- and second-circle casters, and swordsmen with a little magic.","The device: Omahnd's grounding work, boosted for a palace, dressed in our blue. Nobody sells that either.","Total, in gold: not counted; the Treasury has no column for it. Total, in people: two archmages and their apprentice, thrown away. Omahnd licenses its wizards and counts them. Whoever did this had archmages to spare."] }],
          brief: {
            you: "First Caliphina Soraya Anvar, with her attaché and the only two things Halyra has: a wreck that says Omahnd and a prisoner who says Omahnd. What you carried out of that room is what you have.",
            win: "Navid says, in his own words, that the file is too neat and the man is not what he says, and the dispatch is written to look north without naming anyone.",
            room: "Navid reads you as the officer he serves; he will follow an order he thinks is wrong, and he will say so first. Nobody else is here. This is the one room tonight where you may think aloud.",
            lean: "Navid did the sums; the accounting is on the table, and it is the clue: two archmages and their apprentice thrown away, twelve scrolls of a spell nobody sells, a device nobody sells either. Omahnd licenses its wizards and counts them; whoever did this had archmages to spare. Lay out what the room gave you and let him add the intelligence view: Omahnd's covert hands are Blanks with no signature and this man blazed violet; nobody sells Null-Battery work, so a copy means someone with the reach to steal it; if Omahnd wanted the family dead it would not sign the device; a frame this neat wants a war. Candour and command earn his agreement; contempt for his doubts, or a rush to the answer the wreck hands you, gets you a dispatch that says Omahnd. If you came out of the room with nothing, the honest recommendation is Omahnd, and the only way past it is to reason past it aloud.",
            never: "Never order him to write what you have not argued. Never name the Hegemony as a finding; it is a suspicion, and the dispatch says 'the technology may have been obtained' rather than 'the Magisterium did this'.",
          },
          notes: "Navid is loyal, quick and courteous, and has an intelligence view of his own. He has done the accounting of the attempt (on the table): an eighteenth-level phantasmist, a fourteenth-level death-toucher, a third-level apprentice, first- and second-circle casters and swordsmen with a little magic, twelve sixth-circle modified-teleport scrolls, and the device; no gold total, the Treasury has no column for it, and he says so if asked. His reading of it: Omahnd licenses its wizards and counts them, and does not have an eighteenth-level wizard it cannot account for, let alone one to throw away in a dining room; whoever did this had archmages to spare and a scriptorium that scribes a custom sixth-circle spell twelve times. Omahnd's covert agents are Blanks with erased signatures and this man's signature blazed violet before the Caliphara; nobody sells Null-Battery work, so a copy means someone with the reach to steal it; if Omahnd wanted the family dead it would not sign the device; a frame this neat wants a war. He offers these as questions, not conclusions; he follows orders, and says when he thinks one is wrong. If flag cover-broken or bureau-named: Soraya can lay out the accent, the colouring, the casting and the training, Navid confirms with the intelligence view, and the dispatch goes north easily. If flag cover-held: she has the technology, which says Omahnd, and a feeling; the honest recommendation with nothing contrary is Omahnd, the 'omahnd' outcome is the natural one, and only reasoning past it aloud, using Navid's view and her own doubt, earns 'north'. If flag witness-spent: Navid does not mention the prisoner and neither should she; the wreck is all they have. The doubt meter is how far Halyran intelligence is from believing the file. Resolve with one of the outcomes by the last turn.",
          opening: "Ma'am. The wreck says Omahnd, the man says Omahnd, and my stomach says something else. Tell me what the room said, and I will tell you what I think it means.",
          succeedWhen: "Navid says in his own words that the file is too neat and the man is not what he says, and the dispatch is written to look north without naming anyone.",
          failWhen: "Soraya orders the dispatch written to Omahnd's guilt, or lets it stand for want of anything better, or treats his doubts with contempt until he stops offering them.",
          outcomes: {
            "north": { label: "The dispatch looks north", when: "Navid says in his own words that the file is too neat and the man is not what he says, and the dispatch is written to look north without naming anyone.", status: "advance", flags: ["doubt-omahnd"], next: "the-study" },
            "omahnd": { label: "The dispatch says Omahnd", when: "Soraya has the dispatch written to Omahnd's guilt, or lets it stand for want of anything better, or time runs out without the doubt being spoken.", status: "fail", flags: ["omahnd-recommended"], next: "the-study" },
          },
          meters: ["rapport", "doubt"],
          maxTurns: 8,
        },
        {
          id: "the-study",
          title: "The Caliph's study",
          stance: "being-read",
          playerRole: "soraya",
          counterpart: "rashan",
          present: ["sahir"],
          outsider: { mode: "authority", confidence: "high", note: "Her father, who cannot be surprised and does not like feelings. No Warden is in the room." },
          location: "The Caliph's study at dawn; the bruises of the dinner under silk; Sahir by the window with the law's face on.",
          goal: "Tell your father what you believe and make him act on it: a strong statement that names no one, not a war with Omahnd.",
          when: "Dawn. The dispatch is written. Your father has read it, and he has slept, which is more than you have.",
          documents: [{ title: "The accounting of the attempt", body: ["Twelve came. Every one carried a scroll of a sixth-circle teleport, modified for arrival without knowing the room: eyes first, then the man. Twelve scrolls of a spell nobody sells. That is a scriptorium and a season, not a purse.","The dragon that was not a dragon: a ninth-circle phantasm. Nobody casts the ninth circle under the eighteenth level. One archmage, spent on a dining room.","The death-touch tried on the Caliphara: seventh circle, her own design, leaked years ago. Fourteenth level at the least; an archmage, or the next thing to one.","The missiles she grounded: first circle, two bolts. A third-level apprentice of the eighteenth, sent to die beside his master.","The rest, by the Caliphina's count: first- and second-circle casters, and swordsmen with a little magic.","The device: Omahnd's grounding work, boosted for a palace, dressed in our blue. Nobody sells that either.","Total, in gold: not counted; the Treasury has no column for it. Total, in people: two archmages and their apprentice, thrown away. Omahnd licenses its wizards and counts them. Whoever did this had archmages to spare."] }],
          brief: {
            you: "First Caliphina Soraya Anvar, in front of the one man in Halyra who can end this with a word, and who taught you to hate a guess. What the dispatch says is what you are about to defend.",
            win: "Rashan agrees to speak before the Congress and the Court, strongly, naming no one, and to let Halyra look north quietly.",
            room: "Sahir is the law's conscience; he wants a trial, which means evidence, which means time. Your father wants the thing that keeps his family alive and his Congress calm, and he can be talked into a war by a daughter who sounds sure of the wrong thing.",
            lean: "He distrusts feelings and likes evidence; give him the reasons, not the conviction. The accounting is the reason: two archmages and their apprentice thrown away, twelve scrolls of a spell nobody sells; Omahnd counts its wizards, and whoever did this had archmages to spare. Say the numbers and watch him listen. Candour and calm earn him; heat reads to him as a daughter who bled last night and wants someone to pay. If your dispatch said Omahnd, you are arguing against your own paper, and he will notice. If it looked north, he will test it: 'You want me to stand up and say what, exactly?' Have the answer: a warning to whoever, a promise of a finding, and no name.",
            never: "Never tell him it is the Magisterium as a fact; you cannot prove it and he knows it. Never let him hear a war would be simpler. Never mention the Congress inquiry first; let him make the joke.",
          },
          notes: "Rashan is dry, unhurried, a father before a sovereign, and cannot be surprised; he can be convinced, by reasons, never by heat. The accounting of the attempt is on the table and he has read it; if she uses it (the eighteenth-level phantasmist, the fourteenth-level death-toucher, twelve custom scrolls, Omahnd counting its licensed wizards) he listens, and asks what it proves, and accepts 'not who, but not Omahnd' as an answer. He wants the family safe and the Congress calm. He tests her: 'You want me to stand up in front of the Congress and say what, exactly?' and 'Let's not hand the Congress another inquiry.' Sahir speaks rarely and for the law: a trial needs evidence, evidence needs time, and a war needs neither, which is why he is against it. If flag omahnd-recommended: Rashan takes the dispatch at its word and is minded to answer Omahnd with the Armada; the 'war' outcome is the default unless she argues against her own paper with the intelligence view and he is persuaded to a statement instead. If flag doubt-omahnd: he tests her, and if she holds the line with reasons he agrees to a statement that names no one; the 'war' outcome needs her to push him toward Omahnd, or to sound so sure and so hot that he decides certainty is enough. If she cannot convince him of anything he settles for a hedge ('silence'). Resolve with one of the outcomes.",
          opening: "Sit down. Your mother says you bled on my floor and then went and shouted at a prisoner. Tell me you have something better than a feeling.",
          succeedWhen: "Rashan agrees to speak before the Congress and the Court, strongly, naming no one, and to let Halyra look north quietly.",
          failWhen: "Rashan decides Omahnd's guilt is established and orders the Armada to answer it; or he refuses to speak at all and settles for a hedge.",
          outcomes: {
            "statement": { label: "He will speak, and name no one", when: "Rashan agrees to a strong statement before the Congress and the Court that names no one and promises a finding.", status: "advance", flags: ["statement"], next: "the-proclamation" },
            "war": { label: "He answers Omahnd with the Armada", when: "Rashan takes Omahnd's guilt as established, on her paper or her certainty, and orders the Armada to answer it.", status: "fail", flags: ["war"], next: null, ending: "By noon the Humā and the Thirteenth Flotilla are over the Aegis Peaks and the Null-Batteries are lit. Omahnd's denial arrives that evening, and nobody in Halyra is listening to it. The Cadence never sends anyone to a tavern in the north; the ballad is never written; whoever built a device on Omahnd's work gets the war they dressed it for. The Stormwardens never get played." },
            "silence": { label: "He will say something, and mean nothing", when: "Rashan refuses a strong statement and settles for a hedge that names no one and promises nothing.", status: "fail", flags: ["hedge"], next: "the-proclamation" },
          },
          meters: ["rapport", "doubt"],
          maxTurns: 8,
        },
        {
          id: "the-proclamation",
          title: "The proclamation",
          stance: "being-read",
          playerRole: "rashan",
          counterpart: "ambassador",
          present: ["soraya", "sahir"],
          outsider: { mode: "authority", confidence: "medium", note: "Omahnd's ambassador, courteous to the bone, reading the Caliph for resolve because that is what Omahnd will ask him. No Warden is in the room." },
          location: "The Congress hall of the Sky Palace at midday; the Court on the dais, the Congress in its tiers, the Omahndi ambassador in the front row with his hands folded.",
          goal: "Set the tone. Name no one, promise a finding, and make the room hear that Halyra is coming.",
          when: "Noon, the day after the dinner. The dispatch has gone; the Congress has been called; Omahnd's ambassador has asked to be present, and you have let him.",
          brief: {
            you: "Rashan Anvar, Caliph of Halyra, no magic at all, silk over the bruises of the dinner, before the Congress and the Court. Your daughter has told you what she believes; you have decided to speak. Every word goes south tonight.",
            win: "The room hears resolve: powerful, vengeful, and naming no one. The ambassador stiffens and asks leave to send word tonight.",
            room: "The ambassador reads you for Omahnd; Soraya and Sahir read you for the family; the Congress reads you for whether a Caliph without magic can carry this. Whatever you sound like is what Omahnd hears you sound like.",
            lean: "Command and composure carry it; heat is allowed if it is held. Hesitation, apology or a hedge reads as a man who has lost the will to fight, and Omahnd will hear that too, and there are people in the Brass who will find it inspiring. Naming Omahnd is the incident Halyra cannot afford; 'whoever' is the word. Promise a finding, not a war.",
            never: "Never name Omahnd, Tharcia, the Magisterium or anyone. Never promise a war. Never apologise for the dinner.",
          },
          notes: "A proclamation with an audience. The ambassador is the counterpart: measured, courteous, unhurried, a compliment before every knife; he does not know whether his own government did it and will not be made to say so; he answers each of the Caliph's turns with courtesy and reads him for resolve. His tells: fingers still on his cuff when the Caliph sounds certain; a small smile at any hedge; he asks leave to withdraw when he has heard enough. Soraya may steady her father with a look or a word; Sahir may remind the room of the law. The resolve meter is what the room hears. Resolve at 70 or more, or the director judging the tone nailed (command and composure, heat held, no name, a finding promised): 'strong'. Between 35 and 70: 'middling', a statement rather than a warning. Under 35, or hesitation and apology: 'weak'. If the Caliph names Omahnd, Tharcia or the Magisterium: 'named', the incident. If flag hedge: he arrives with a hedge in his pocket and must find resolve in the room or fall to 'weak'. Resolve with one of the outcomes by the last turn, and let the resolution sentence say what Omahnd does next.",
          opening: "Majesty. The Caliphate of Omahnd shares Halyra's grief, and I am instructed to hear whatever Halyra wishes to say. By the Measure, we are listening.",
          succeedWhen: "Resolve reaches 70, or the director judges the tone nailed: powerful, vengeful, naming no one, promising a finding.",
          failWhen: "Resolve ends under 35, or the Caliph hedges, apologises, or names Omahnd, Tharcia or the Magisterium.",
          outcomes: {
            "strong": { label: "The room heard resolve", when: "Resolve at 70 or more, or the tone nailed: powerful, vengeful, naming no one, promising a finding. The ambassador stiffens and asks leave to send word tonight.", status: "advance", flags: ["omahnd-denied-quick"], next: "your-deniables" },
            "middling": { label: "A statement, not a warning", when: "Resolve between 35 and 70: the room heard a Caliph, not a promise.", status: "advance", flags: ["omahnd-slow-denial"], next: "your-deniables" },
            "weak": { label: "The room heard a man who had lost the will to fight", when: "Resolve under 35, or hesitation, apology or a hedge the ambassador smiles at.", status: "fail", flags: ["omahnd-emboldened"], next: null, ending: "Omahnd's answer comes three days late and says nothing. In the tea houses of the Golden Ledger the talk is that the Sky Caliph sounded like a man who had lost the will to fight, and there are those in the Brass who begin to think the thing they did not do might be worth having done. The file stands. Halyra looks south, and keeps looking. The Stormwardens never get played." },
            "named": { label: "He named Omahnd", when: "The Caliph names Omahnd, Tharcia or the Magisterium before the ambassador.", status: "fail", flags: ["war"], next: null, ending: "The ambassador withdraws before the Caliph has finished. By nightfall the Brass Frontier is closed and the Null-Batteries are lit, and nobody on either side is asking who built the device any more. The Cadence never sends anyone to a tavern in the north. The Stormwardens never get played." },
          },
          meters: ["resolve", "standing"],
          maxTurns: 6,
        },
        {
          id: "your-deniables",
          title: "Your deniables",
          stance: "being-read",
          playerRole: "navid",
          counterpart: "varya",
          present: ["tav"],
          outsider: { mode: "authority", confidence: "medium", note: "An officer of the Sky Armada, in uniform, buying deniable hands in the open: authority until his anxiety makes him something to doubt, or his tone makes them hirelings." },
          location: "The back room of the AKA In; the Shahin moored outside; two Armada officers at the door; three cups on the table and the intelligence folio between them.",
          goal: "Hire the Stormwardens in the open and keep Halyra's suspicion out of your mouth: the Omahnd file first, the Hegemony never.",
          when: "Weeks after the dinner. The Cadence sent them; the Shahin brought you. Halyra has a file that says Omahnd, and does not believe it.",
          documents: [{ title: "The Omahnd file", body: ["The device that tilted the Sky Palace: built on the grounding work of the Caliphate of Omahnd's Null-Batteries, boosted to a palace's scale, in Halyra's own blue. The signature is Omahnd's. Nobody else makes it.","Twelve assassins by teleport, black-robed, violet-handed. Two survived. One is a pig.","Spent on the attempt: an eighteenth-level phantasmist, a fourteenth-level death-toucher, an apprentice, and scrolls for twelve.","Omahnd's answer, within the day: grief, condemnation, denial, an offer of full cooperation.","Assessment: every indication points to the Caliphate of Omahnd.","In the margin, in a different hand: too complete."] }],
          brief: {
            you: "Lieutenant Navid Qasran, Sky Armada Intelligence, in uniform, the Shahin moored outside and two of your officers at the door. You speak for the Imperial family and for the Caliph himself.",
            win: "Varya takes the job in her own words, or Tav names a price and she lets it stand, and the Hegemony's name has never left your mouth.",
            room: "Varya reads the file and reads you; Tav reads the room and says the thing under it. They know exactly who is paying: the seal on the contract will be the Armada's. Your officers hear everything, and so would anyone at the bar. Behind you is a war with Omahnd that has run cold and hot for hundreds of years; Halyra is trying not to provoke an international incident on a file it does not trust. Omahnd condemned the attack and denied it publicly, which is what anyone would do, but they were quick, and the evidence is too neat. That is what Halyran intelligence believes, and you may say so. What Halyra wants with the evidence is not a war: the planner's confession, warranted, signed and delivered, to put before the Magisterium and demand the extradition of those responsible for trial and punishment. Halyra suspects an official plot and expects the Magisterium to hand over one wizard, or a few, rather than fight. In the room that is 'the guilty party', and no more.",
            lean: "Courtesy first: they are guests, not hirelings, and Tav goes cold at the first hint of a hireling's tone. Put the Omahnd file on the table and let it be too complete; when Tav says so, agree with your face. When Varya says the Hegemony's name, do not confirm it: 'We are asking you to find who did this.' What they need to hear: bring us evidence and warrants Halyra can carry to the guilty party, keep it at arm's length, this conversation never happened. Composure and candour earn the commission; anxiety, and she presses on what you are not saying.",
            never: "Never say the Cinnabar Hegemony's name, or the Magisterium's, and never confirm it when she does. Never pretend Halyra believes the Omahnd file. The contract can be signed and sealed in the open; the suspicion is what never happened.",
          },
          notes: "Played as shot in the deleted briefing. Navid arrives on the Shahin in uniform with two officers; the officers stop the Wardens at the door and Navid waves them in as guests ('These are our guests. Do not be so rude. They have come to help us, no?'). He names Soraya, the Imperial family and the Caliph in his first breath; Tav turns the title over ('Caliphina... Princess?' 'Exactly that, in the trade-lang'). The folio goes on the table: assassins of unusual power teleported into the family's private dinner; every indication points to the Caliphate of Omahnd. Tav, from the file: 'And they're worried it's too complete. Too definitive.' Navid's face agrees. Varya: 'Then someone very badly wants you to blame Omahnd. You're looking at the Cinnabar Hegemony?' Navid must answer 'No. We are asking you to. Find who did this, bring us evidence and warrants Halyra can carry to the guilty party, and keep it at arm's length. This conversation never happened.' The commission is formal and will be sealed under the Armada's wings; deniability is the suspicion, never the hire. Varya reads him: anxiety in his voice and she presses on what he is not saying; a hireling's tone and Tav's charm goes cold; composure and candour earn it. Tav may name a price. Varya may say 'Close the door' to end it either way. If Navid names the Hegemony or the Magisterium as Halyra's suspicion, the deniability is gone and the scene fails. Halyra's reason for the arm's length: a cold-and-hot war with Omahnd running for hundreds of years, and no wish to provoke an international incident on a file it does not trust; Omahnd condemned the attack and denied it publicly, quickly, and the evidence is too neat, which is what Halyran intelligence believes. If flag omahnd-denied-quick: Navid may say Omahnd's denial came fast and hard, which is what you would do, but they were quick. If flag omahnd-slow-denial: the denial came slow and formal, Halyra is less sure, and Navid must lean on the technology and the prisoner to carry the doubt. If flag bureau-named: Navid knows the purple was named in the palace and still will not say it here. Navid may say all of that; it is the Hegemony's name he may not. Halyra's purpose with the warrants: to present the planner's confession, warranted, signed and delivered, to the Magisterium and demand extradition of those responsible for trial and punishment, expecting it to hand over one wizard or a few rather than start a war; Halyra suspects an official plot. Navid says 'the guilty party' and lets them hear the rest. Never let him state the sponsor's wider objective; the story keeps it open.",
          opening: "You brought a warship to a tavern, Lieutenant. Whatever this is, it was not an impulse request. Sit. Tell me.",
          succeedWhen: "Varya accepts the job in her own words, or Tav names a price and she does not object, with Navid never having named the Hegemony or the Magisterium.",
          failWhen: "Navid names the Hegemony or the Magisterium as Halyra's suspicion; or suspicion reaches 85 and she concludes Halyra is setting them up as patsies; or rapport reaches zero and she says 'Close the door'.",
          meters: ["cover", "suspicion", "rapport"],
          maxTurns: 8,
        },
      ],
    },
    {
      id: "tour",
      title: "Act II. Make It Famous",
      summary: "Six months on the road across Tharcia. Posters, screaming fans, a count at every stop, and the ones who talk.",
      beats: [
        {
          id: "make-it-famous",
          title: "Make it famous",
          stance: "being-read",
          playerRole: "tav",
          counterpart: "heckler",
          present: ["thorbin", "brask", "lyra"],
          outsider: { mode: "nuisance", confidence: "medium", note: "A heckler until he counts the room or his hands light, then a predator. A nuisance is not a combat encounter." },
          location: "A packed tavern, standing room only, the poster on the wall; Thorbin at the bar, Brask by the back passage, Lyra not drinking anything from in here.",
          goal: "Make the room love you and let the ballad's exaggerations do their work. Notice who reacts to the wrong details.",
          when: "Weeks into the six months. The ballad has been sung in other towns; tonight it is bait.",
          brief: { you: "Tavian Larkvale, on the dais, with the ballad. The room is reading you.", win: "Fame reaches 70, or the heckler reacts to a planted error in a way the room can see.", room: "Thorbin, Brask and Lyra are in the crowd. A red-robed heckler wants the pork verse sung again, because he knows what is wrong with it.", lean: "Showmanship raises fame. Anxiety raises suspicion, and the troupe is terrible at staying inconspicuous. Let him react; do not explain the tell.", never: "Suspicion at 85 turns the room. Naming the Bureau to his face lights his hands, and that is a fight, not a win." },
          notes: "The player performs and banters; showmanship raises fame. The heckler baits him about the pork verse because he knows it is wrong about who cast it: reacting to that is his self-identification, and the director should let the tell show rather than say it. Anxiety in Tav's voice raises suspicion; the troupe must stay inconspicuous, which they are terrible at. If suspicion climbs past 85 the room turns and this becomes the run-out-of-town night. The heckler's hands may ignite if the ballad names the Bureau to his face.",
          opening: "Sing the pork verse again, minstrel. I want to hear who you say cast it.",
          succeedWhen: "Fame reaches 70, or the heckler reacts to a planted error in a way the room can see.",
          failWhen: "Suspicion reaches 85 and the room turns.",
          meters: ["fame", "suspicion"],
          maxTurns: 8,
          force: { threat: "The heckler's hands ignite violet and the room scatters.", requires: ["muscle", "concurrence"], scale: "scuffle" },
        },
        {
          id: "the-alley",
          title: "So who did do the planning, lad?",
          stance: "reading",
          playerRole: "thorbin",
          counterpart: "heckler",
          present: ["brask", "serena", "varya"],
          outsider: { mode: "predator", confidence: "high", note: "Held, not yet charged: the moment Serena takes custody, protecting him becomes real; the pressure is Brask's forearm, never words." },
          location: "The alley behind the tavern; Brask's forearm across the man's chest; a lit window above where Varya writes beside Serena.",
          goal: "Get an admission Serena can swear to. Tyr takes no hearsay, so the words must be his.",
          when: "The same night, behind the tavern. Brask has the heckler against the wall and Serena is listening.",
          brief: { you: "Thorbin Ironhart, questioning a man who thinks you beneath notice.", win: "He admits, in his own words, that he was sent to hear the ballad and count who came, or names the Bureau's interest in it.", room: "Brask supplies the pressure without a word. Serena is listening: Tyr takes no hearsay, so the words must be his. This is the confession Halyra will carry to the Magisterium to demand extradition for trial, so it must be sworn and beyond recanting. Varya's look asks whether it is enough; Serena's head-shake means not yet.", lean: "Warmth and patience open him more than pressure. He talks down to a dwarf and does not look up until it is too late.", never: "Do not put words in his mouth. If he tries a word of power the scene tips, and Lyra is not in the alley." },
          notes: "He talks down to a dwarf and does not look up until it is too late. Thorbin's warmth and patience open him more than pressure; Brask supplies the pressure without a word. Evidence moves only on usable admission in his own words within Serena's hearing; Varya's look asks 'Is that enough?' and Serena's head-shake means not yet. If he tries a word of power the scene tips; Lyra is not in the alley, so cover is short.",
          opening: "Do I know you, half-man?",
          succeedWhen: "He admits, in his own words, that he was sent to hear the ballad and count who came, or names the Bureau's interest in it.",
          failWhen: "Rapport reaches zero, or he is silenced by a fight that goes badly.",
          meters: ["standing", "rapport", "evidence"],
          maxTurns: 10,
          force: { threat: "He tries a word of power with Brask's forearm across his throat.", requires: ["muscle", "concurrence", "legitimacy"] },
        },
        {
          id: "stay-inconspicuous",
          title: "Stay inconspicuous",
          stance: "being-read",
          playerRole: "varya",
          counterpart: "watch-captain",
          present: ["tav", "brask"],
          outsider: { mode: "authority", confidence: "high", note: "A competent, brusque captain doing real work; never a predator. Cooperate, assess jurisdiction, manage face, ask for the concrete rule." },
          location: "The watch house of a Tharcian market town, the morning after the mob; the carriage impounded in the yard.",
          goal: "Get the troupe released with the carriage and no names written down.",
          when: "The morning after. A Magisterium wizard is missing and your carriage is in the captain's yard.",
          brief: { you: "Varya Stormveil, in the captain's chair, with Tav and Brask beside you.", win: "He releases the troupe and the carriage without writing a name down.", room: "The captain is Tharcian, not Rubrican. He wants the paperwork closed and the Magisterium out of his town.", lean: "Say little. Stillness reads as authority; anxiety reads as guilt. Tav's charm helps until it becomes performance. Brask's literal answers are dangerous and funny.", never: "Suspicion at 85 sends for a magistrate. If cudgels come out you have muscle and a face on hand, but that is the run-out-of-town night." },
          notes: "The captain is Tharcian, not Rubrican; he wants the paperwork closed and the Magisterium out of his town. Varya says little; stillness reads as authority, anxiety reads as guilt. Tav's charm helps until it becomes performance. Brask's literal answers are dangerous and funny. If cudgels come out, the troupe has muscle and a face on hand.",
          opening: "A wizard of the Magisterium goes missing the night your troupe plays, and you would like your carriage back.",
          succeedWhen: "He releases the troupe and the carriage without recording names.",
          failWhen: "Suspicion reaches 85 and he sends for a magistrate.",
          meters: ["cover", "suspicion"],
          maxTurns: 8,
          force: { threat: "The captain's men reach for their cudgels.", requires: ["muscle", "face"], scale: "scuffle" },
        },
        {
          id: "morning",
          title: "Morning.",
          stance: "reading",
          playerRole: "serena",
          counterpart: "sleeper",
          present: ["kael", "lyra", "brask"],
          outsider: { mode: "mixed", confidence: "high", note: "A frightened hostile wizard: custody and evidence can coexist. Kael protects first; Serena leads nowhere." },
          location: "A snowy cottage bedroom in the middle of the night; Kael's hands over the wizard's; Lyra already in the corner; Brask on the stairs with a red blanket.",
          goal: "Take his testimony yourself. A paladin swears only to what her own ears heard, so lead nowhere; let him speak.",
          when: "Nights later, a cottage in the snow, the middle of the night. A Magisterium wizard, woken in his own bed.",
          brief: { you: "Serena Duskbane, taking testimony, with Kael, Lyra and Brask in the room.", win: "He states, unprompted, what the Bureau wanted from the ballad's audience.", room: "A paladin swears only to what her own ears heard. If you lead him, what he says does not count. What you swear to is what Halyra puts before the Magisterium to demand extradition for trial; a word of yours in his mouth and the case is gone.", lean: "Calm certainty earns standing; warmth earns rapport; pressure frightens him into noise that is not testimony. He knows what the Bureau wanted from the audience and nothing of the wider plan.", never: "Lead him three times and the testimony is gone." },
          notes: "Serena must not put words in his mouth; if the director judges she led him, evidence does not move. Calm certainty earns standing; warmth earns rapport; pressure frightens him into noise that is not testimony. He knows what the Bureau wanted from the ballad's audience and nothing of the wider objective.",
          opening: "But it's the middle of the night.",
          succeedWhen: "He states, unprompted, what the Bureau wanted from the ballad's audience.",
          failWhen: "He is silenced by a fight that goes badly, or the director judges Serena led him three times.",
          meters: ["evidence", "rapport", "standing"],
          maxTurns: 8,
          force: { threat: "Blue spell-light gathers in his palms under Kael's hands.", requires: ["concurrence", "muscle"], scale: "scuffle" },
        },
        {
          id: "the-carriage",
          title: "You're difficult people to catch",
          stance: "reading",
          playerRole: "varya",
          counterpart: "visitor",
          present: ["tav", "brask", "serena"],
          outsider: { mode: "mixed", confidence: "low", note: "Unhurried, employer unnamed: read him on behaviour alone and reclassify on evidence. The letter, not the man, is the object." },
          location: "A wet town square; the poster-covered carriage; a man in burgundy robes inside it with a letter.",
          goal: "Decide whether the letter is a lead or a leash, and take it on your terms.",
          when: "Dusk, late in the tour. A stranger at the step of your carriage with a letter and no employer's name.",
          brief: { you: "Varya Stormveil, inside the troupe's carriage, with Tav, Brask and Serena near.", win: "Take the letter and its terms without the employer being named.", room: "The visitor is never hurried and never names his employer. It resolves on 'Close the door'.", lean: "Stillness earns standing; curiosity earns the letter; pressure amuses him.", never: "Rapport at zero and he leaves with the letter. The name of the town it points to stays unspoken." },
          notes: "The visitor is never hurried and never names his employer; the director must not either. Varya's stillness earns standing; curiosity earns the letter; pressure amuses him. The beat resolves on 'Close the door': the letter carries the lead to the final town, whose name stays unspoken.",
          opening: "You're difficult people to catch.",
          succeedWhen: "Varya secures the letter and its terms without the employer being named.",
          failWhen: "Rapport reaches zero and he leaves with the letter, or a fight goes badly.",
          meters: ["standing", "rapport", "evidence"],
          maxTurns: 8,
          force: { threat: "The visitor's smile does not change as his hand finds something under the paper.", requires: ["blade", "brains", "stealth"] },
        },
      ],
    },
  ],
  clips: [
    ...reactions("indigo", "a bound Murex Bureau assassin in a grounded cell, black robes torn, violet embers dead in his eyes", "windowless stone room lit by blue anchor-light"),
    ...reactions("varya", "Varya Stormveil, dark practical clothing, a ledger open under her hand", "the low back room of a tavern by lamplight"),
    ...reactions("heckler", "a young red-robed Magisterium functionary, sneer fading", "a packed tavern, then a wet alley at night"),
    ...reactions("watch-captain", "a weary provincial watch captain behind a desk", "a stone watch house at grey morning"),
    ...reactions("sleeper", "a middle-aged wizard in a nightshirt, pinned hands, snow at the window", "a snowy cottage bedroom by candlelight"),
    ...reactions("visitor", "a smooth man in burgundy robes seated inside a carriage, a sealed letter in his hand", "the inside of a poster-covered carriage in rain"),
    establishing("sky-palace-cell", "Establishing shot, a windowless room in a sky palace, blue anchor-lights set into pale stone walls, a bound figure at the far wall, gold light from a doorway. Photoreal, slow push-in, 6 seconds."),
    establishing("aka-in-back-room", "Establishing shot, the back room of a tavern by lamplight, a Sayah-class sky cutter's hull visible through a rear window, a lute on the table. Photoreal, slow push-in, 6 seconds."),
    establishing("packed-tavern", "Establishing shot, a standing-room-only tavern, a bard on a dais, a poster on the wall, a red-robed man at the back. Photoreal, slow dolly, 6 seconds."),
    establishing("the-alley", "Establishing shot, a wet alley behind a tavern at night, a huge man holding a red-robed wizard to the wall, a lit window above. Photoreal, static, 6 seconds."),
    establishing("watch-house", "Establishing shot, a provincial watch house at grey morning, an impounded carriage in the yard beyond the window. Photoreal, slow pan, 6 seconds."),
    establishing("snowy-cottage", "Establishing shot, a snowy cottage at night, one candle in an upstairs window, footprints to the door. Photoreal, slow push-in, 6 seconds."),
    establishing("wet-square-carriage", "Establishing shot, a wet town square at dusk, a poster-covered carriage, a door opening onto a seated figure. Photoreal, slow dolly, 6 seconds."),
  ],
  prohibitions: [
    "Varya, never Veyra, Verya or Varia. Piss and Moan, never Piss and Vinegar. Serena is not Lord Marshal. Ogma not Oghma. Concurrence not Weave. Morrighad not Moradin. The Cadence, not Harpers. Tharcia and the Rubrican Magisterium, never Thay or Red Wizards. AKA In is the spelling.",
    "SEALED: never reconstruct, infer or invent Thorbin's third loss at Mhasun; in text it is a failure to pick up a stone in time, carried unstoned, and the narrator is never told.",
    "SEALED: never identify or hint at the source of Kael's power; the Stormwardens do not know it.",
    "SEALED: never explain the source, purpose or destination of Laleh's call north; she does not know why.",
    "OPEN: never name the assassins' sponsor's objective beyond attacking the dynasty, the surviving assassins' identities, the carriage visitor's employer, or the final town.",
    "The ballad never attributes the pig polymorph. Soraya commissioned the Stormwardens; the deniables never say so aloud in Act II.",
    "Never escalate a palace beat into violence. Never let Soraya threaten restoration or severance.",
  ],
};

export const shadowFell = defineWorld(pack);
