import { defineWorld, type Clip, type WorldInput } from "../../engine/world.js";

/**
 * The Shadow Fell: the unshown middle of Death Came to Dinner.
 * Working title drawn from the Halyran idiom for intelligence taking an interest.
 * Cast, lines and places come from the Bright Ruin vault's in-text canon; minor
 * functionaries (the heckler, the watch captain, the sleeper, the visitor) are
 * working material for Jon's canon check.
 */

const ROYAL_VOICE = "Refined, regal British Empire accent";
const COMMONER_VOICE = "Warm North African French-accented voice, Arabic-inflected, melodic";

const TAGS: Array<{ tag: Clip["tag"]; look: string }> = [
  { tag: "warming", look: "softens, the guard coming down a fraction, eyes staying on the speaker" },
  { tag: "cooling", look: "hardens, jaw set, a small withdrawal of the shoulders" },
  { tag: "shock", look: "caught out, a breath held, eyes widening for one beat" },
  { tag: "bored", look: "unimpressed, a slow blink, attention drifting to the door" },
  { tag: "calculating", look: "watching, weighing, a thought arriving behind the eyes" },
  { tag: "pressed", look: "under pressure, a swallow, hands finding something to hold" },
  { tag: "neutral", look: "listening, still, giving nothing away" },
];

function reactions(character: string, subject: string, setting: string): Clip[] {
  return TAGS.map(({ tag, look }) => ({
    key: `${character}-${tag}`,
    kind: "reaction" as const,
    character,
    tag,
    prompt: `Cinematic close-up, ${subject}, ${setting}. Reaction: ${look}. Photoreal, shallow depth of field, one continuous take, 5 seconds, no dialogue.`,
  }));
}

function establishing(key: string, prompt: string): Clip {
  return { key, kind: "establishing", tag: "neutral", prompt };
}

const pack: WorldInput = {
  id: "shadow-fell",
  title: "The Shadow Fell",
  tagline: "Halyran intelligence has taken an interest. The world listens to how you say it.",
  premise:
    "Between the assassination at the Caliph's table and the sting at the AKA In, two investigations run toward the same final town. In the Sky Palace, First Caliphina Soraya Anvar and Lt. Navid Qasran question the survivors and hire deniable northern hands. On the road, the Stormwardens spend six months making a ballad famous across Tharcia, counting who comes to hear it and taking the ones who talk. Every character reacts to how you sound, not to what you meant.",
  narrator: "scribe",
  palette: {
    ivory: "#F3EBDD",
    parchment: "#E6D8BC",
    oldGold: "#C8A24A",
    whiteGold: "#F5E6B8",
    brush: "#141210",
    stateBlue: "#1E5F8A",
    cerulean: "#2E86B5",
    stormViolet: "#5B3E8C",
    crimson: "#8B1E2D",
  },
  cast: [
    {
      id: "scribe", name: "The Scribe", faction: "the Stormwardens", summary: "The hand that letters 'The Stormwardens Present:'. Narrates scene cards and the outcome of a fight in the past tense of a told tale.",
      register: "Storyteller, warm, spare.", voice: { name: "Shadow Fell Scribe", description: "Older narrator, unhurried, a scribe reading his own fair copy" },
    },
    {
      id: "soraya", name: "Soraya Anvar", title: "First Caliphina, Captain of the CAA Humā", faction: "House Anvar",
      summary: "Air archmage, ship designer, sits in Congress, senior captain of the flagship. Direct, blunt, funny; corrects immediately and theatrically, cares afterward. Took custody of the survivors: 'Alive, silent, and mine.' Has already been the subject of one congressional inquiry over interrogation methods; her father still answers the letters.",
      register: `${ROYAL_VOICE}; quick, dry, a commander's ease.`, voice: { name: "Soraya", description: `${ROYAL_VOICE}; a woman of 28 with a commander's ease; quick, direct, amused` },
      capabilities: ["command", "concurrence"], lines: ["Alive, silent, and mine.", "Nobody heals what I can't question."],
      portrait: "/portraits/soraya.svg",
    },
    {
      id: "navid", name: "Navid Qasran", title: "Lieutenant, Sky Armada Intelligence", faction: "Halyran Intelligence",
      summary: "27, Imperial Military Attaché, Soraya's trusted man. Commoner register; quick, courteous, formal only when the moment demands. Hires the deniables at the AKA In and later delivers 'Halyran intelligence heard from your deniables, ma'am.'",
      register: `${COMMONER_VOICE}; courteous, quick, a smile in it.`, voice: { name: "Navid", description: `${COMMONER_VOICE}; a man of 27, quick and courteous` },
      capabilities: ["face", "brains"], lines: ["These are our guests, do not be so rude. They have come to help us, no?"],
      portrait: "/portraits/navid.svg",
    },
    {
      id: "indigo", name: "The Indigo", title: "Surviving assassin, Murex Bureau", faction: "the Murex Bureau",
      summary: "One of the two dragon-blasted assassins who survived the dinner; bound in Kaveh's mesh, grounded, kept breathing 'and not a breath more'. Born to the purple. Fears the Eminence more than any Anvar. Identity unresolved and must stay so.",
      register: "Clipped, superior, tired; contempt as a habit, fear underneath it.", voice: { name: "Shadow Fell Indigo", description: "A grounded wizard in custody: clipped, superior diction, tired, contempt worn thin" },
      tells: ["glances at his bound hands whenever the Bureau is named", "laughs a beat late at threats", "goes completely still at the word 'trial'"],
      knows: ["The device wore Halyra's state blue on orders, so nobody would question a blue device near the service door.", "The word 'Bureau' and the title 'the Eminence'; he will not say the sponsor's objective and the director must not invent one.", "That the Congress would hear of any cruelty; he will try to provoke it."],
      portrait: "/portraits/indigo.svg",
    },
    {
      id: "rashan", name: "Rashan Anvar", title: "Caliph of Halyra", faction: "House Anvar",
      summary: "52, no magic at all, warrior-diplomat, cannot be surprised by vigilance alone. Hospitality is a martial art. Dry, unhurried, a father before a sovereign.",
      register: `${ROYAL_VOICE}; dry, unhurried.`, voice: { name: "Rashan", description: `${ROYAL_VOICE}; a man of 52, dry, unhurried, amused` },
      lines: ["Guests, then. The worst kind.", "Let's not hand the Congress another inquiry."],
    },
    {
      id: "sahir", name: "Sahir Anvar", title: "First Caliphant, heir", faction: "House Anvar",
      summary: "31, the law's conscience. Speaks rarely; the room stills when he does.",
      register: `${ROYAL_VOICE}; few words, each weighed.`, voice: { description: `${ROYAL_VOICE}; a man of 31, measured, quiet` },
      lines: ["Dead men serve their masters. Living men betray them.", "And alive to reach trial."],
    },
    {
      id: "tav", name: "Tavian Larkvale", title: "Bard, the ballad's author", faction: "the Stormwardens",
      summary: "28, bard-strategist, celerity, co-lead, the face, undercover as the entertainment. Charm as tempo. Keeps the future open; can turn every crisis into motion before others consent.",
      register: "Northern performer's warmth; quick, musical, a grin you can hear. Narrates his own reaction under tension ('Him?? This kid??'), then files it.", voice: { name: "Tavian", description: "A charming bard of 28, warm, quick, musical phrasing, a grin in the voice" },
      capabilities: ["face", "brains", "blade"],
      moves: [{ id: "rapier", label: "Tav's rapier is already at his back", capability: "blade", bonus: 0.1, line: "Talk, or die. It is your choice. We get paid either way." }],
      lines: ["Talk, or die. It's your choice. We get paid either way."],
      portrait: "/portraits/tav.svg",
    },
    {
      id: "serena", name: "Serena Duskbane", title: "Paladin of Tyr", faction: "the Stormwardens",
      summary: "30, certitude, co-lead, refused Lord Marshal. Tyr takes no hearsay: she swears only to what her own ears witnessed, so a confession within her hearing is sworn testimony. Composed, persuasive, closes on what must be done.",
      register: "Calm, level, every sentence already decided; wins with one word ('Denied.').", voice: { name: "Serena", description: "A paladin of 30, calm, level, certain, warm underneath" },
      capabilities: ["legitimacy", "blade"],
      moves: [
        { id: "radiant", label: "Serena's blade ignites", capability: "blade", bonus: 0.15, line: "Surrender or die. Decide now." },
        { id: "court", label: "Serena convenes the court", capability: "legitimacy", bonus: 0.1, line: "You've just confessed in front of a paladin of Tyr." },
      ],
      lines: ["Tyr takes no hearsay.", "You've just confessed in front of a paladin of Tyr."],
      portrait: "/portraits/serena.svg",
    },
    {
      id: "thorbin", name: "Thorbin Ironhart", title: "Cleric of Morrighad", faction: "the Stormwardens",
      summary: "About 187 and not certain himself. Dwarf, cleric-maker, family anchor, the bait by choice; a florid orator, warm and patient, terrifying when still. Struck at Mhasun twice, forty years apart: the first time as leader of his own party and its only survivor; the second time held and profiled there while the others destroyed its records. A Bureau field-ring keyed to his signature flares when the enemy is near. Morrighad is very persuasive beyond the veil.",
      register: "Florid, rolling, fond; 'lad' and 'laddie'; the warmth never quite leaves even when the threat arrives. Calls Tav, Serena and Lyra 'the Kids', even now.", voice: { name: "Thorbin", description: "An old dwarf cleric, deep, rolling, fond, florid phrasing, patient" },
      capabilities: ["bait", "healing", "muscle"],
      moves: [{ id: "hammer", label: "Thorbin slaps the haft of the big hammer", capability: "muscle", bonus: 0.1, line: "Goin' somewhere are ye, laddie?" }],
      lines: ["So who did do the planning, lad?", "This hurts us more than it hurts you.", "Morrighad is very persuasive beyond the veil."],
      portrait: "/portraits/thorbin.svg",
    },
    {
      id: "varya", name: "Varya Stormveil", title: "Cadence operative", faction: "the Stormwardens",
      summary: "33, legendary Cadence operative, systems hunter, the brains. Silence is power: confirms outcomes, refuses narration, one sentence of rationale then execution. Keeps the ledger. An interrogator by tradecraft. Polite stillness that terrifies authority.",
      register: "Few words, flat, exact; never explains; the pause is the sentence. Silence is how she says yes.", voice: { name: "Varya", description: "A woman of 33, low, flat, exact, unhurried, quiet authority" },
      capabilities: ["brains", "stealth", "blade"],
      moves: [
        { id: "piss-and-moan", label: "Varya's hatchets fly and come back", capability: "blade", bonus: 0.2, line: "Piss and Moan return to her hands before he understands he was hit." },
        { id: "cloak", label: "Varya is simply not there", capability: "stealth", bonus: 0.15, line: "The hood goes up and the alley has one fewer person in it." },
      ],
      tells: ["writes in the ledger while you speak", "a look to Serena: is that enough?"],
      lines: ["Men who talk down don't look up until it's too late.", "Close the door.", "Preventive measure."],
      portrait: "/portraits/varya.svg",
    },
    {
      id: "brask", name: "Brask Runebearer", title: "Qoranhi barbarian", faction: "the Stormwardens",
      summary: "34, muscle and spectacle, literalist, moral perceiver. Reveals hidden premises by taking language seriously. His axe is Souldrinker.",
      register: "Broken Common, by canon, second language: third person, 'Brask'; TO BE and TO DO unstable ('He angry.' 'Why you here?' 'You know him?' 'What he say?'); time by time words and sequence, never conjugation ('Yesterday he go north.' 'You make promise. Promise fail.'); 'no' or 'not' before the verb ('We not know.'); nouns plus action words for native verbs and abstractions ('You give word. Then break word.' 'I ask. You not answer.'); possession over containment ('You say two wagons. What they have?'); articles dropped unless needed; short units, fact, fact, question, consequence; connectors only and, but, so, because, if, then, before, after; no native idioms; abstraction turned into concrete variables ('What he gets if he lies?'); precise words in his own domains; a simple line stays inside the rail ('That not true.'). His intelligence shows in which question comes next, never in his syntax. 'Easier. Less production.' Calls Thorbin 'dwarf master'.", voice: { name: "Brask", description: "A huge steppe warrior, deep, slow, few words, literal" },
      capabilities: ["muscle", "spectacle"],
      moves: [{ id: "souldrinker", label: "Brask brings Souldrinker down", capability: "muscle", bonus: 0.15, line: "Half man, is it? How much man is Brask and friends?" }],
      lines: ["We practise.", "Why can't you just say 'you thirsty'? Easier. Less production."],
      portrait: "/portraits/brask.svg",
    },
    {
      id: "lyra", name: "Lyra Veyrin", title: "Sorceress", faction: "the Stormwardens",
      summary: "26 presenting about 24, elf, raw channeler; the Concurrence shows her extraordinary reciprocity. Dry, sly, disdainful of holes.",
      register: "Dry, sly, unimpressed; deadpan disdain. Addresses Thorbin as 'Master Cleric'; 'acceptable, slightly literal' is high praise.", voice: { name: "Lyra", description: "A young elf woman, dry, sly, deadpan, faintly disdainful" },
      capabilities: ["concurrence"],
      moves: [{ id: "cut-off", label: "Lyra asks the Concurrence nicely", capability: "concurrence", bonus: 0.2, line: "The Concurrence only cuts people off when she asks it really nicely." }],
      lines: ["The Concurrence only cuts people off when I ask it really nicely.", "This place is a total hole. I am not drinking anything from in here."],
      portrait: "/portraits/lyra.svg",
    },
    {
      id: "kael", name: "Kael Thornmere", title: "Druid", faction: "the Stormwardens",
      summary: "19, druidic prodigy, ecological listener, the conscience who volunteers. Receives nature rather than commanding it. Gentle, exact.",
      register: "Soft, exact, young; a kindness that does not bargain. Asks, never tells ('They're mine to ask.').", voice: { name: "Kael", description: "A young man of 19, soft, exact, gentle, unhurried" },
      capabilities: ["concurrence", "healing"],
      moves: [{ id: "vine", label: "Kael says one sentence to the vine", capability: "concurrence", bonus: 0.15, line: "A length of vine, a single sentence, and the hands are no longer his to use." }],
      lines: ["Morning.", "Then you haven't missed anything."],
      portrait: "/portraits/kael.svg",
    },
    {
      id: "heckler", name: "The Heckler", title: "A red-robed man of the Magisterium", faction: "the Rubrican Magisterium",
      summary: "A junior functionary sent to hear the ballad and count what it knows. Talks down to dwarves and up to no one. Reacts to the ballad's planted exaggerations because he knows which details are wrong. Working material.",
      register: "Clipped, superior, a little bored; contempt for 'half-men'.", voice: { name: "Shadow Fell Heckler", description: "A superior young wizard, clipped, bored, sneering" },
      tells: ["reacts to the wrong details of the ballad, not the right ones", "looks for the exits when the song names the Bureau", "calls Thorbin 'half-man' and then cannot stop watching him"],
      knows: ["He was sent to hear the ballad and report who else came.", "He knows the pork verse is wrong about who cast the spell, which is exactly the trap."],
      portrait: "/portraits/heckler.svg",
    },
    {
      id: "watch-captain", name: "The Watch Captain", title: "Captain of a Tharcian town watch", faction: "Tharcia",
      summary: "Tharcian, not Rubrican: a townsman with a job, tired of wizards and of troupes. Wants the paperwork to close. Working material.",
      register: "Provincial, weary, procedural; would rather be at breakfast.", voice: { name: "Shadow Fell Watch Captain", description: "A weary provincial officer, middle-aged, procedural, dry" },
      tells: ["softens when the troupe makes his paperwork easier", "stiffens at any mention of the Magisterium"],
      knows: ["A red-robed wizard went missing the night the troupe played.", "He does not want the Magisterium in his town any more than the Wardens do."],
      portrait: "/portraits/watch-captain.svg",
    },
    {
      id: "sleeper", name: "The Sleeping Wizard", title: "A Magisterium wizard in a snowy cottage", faction: "the Rubrican Magisterium",
      summary: "Woken in the middle of the night to find Kael, Serena and Lyra already in the room. Frightened, proud, and, once his hands are pinned, honest in the way frightened people are. Working material.",
      register: "Sleep-thick, indignant, then careful.", voice: { name: "Shadow Fell Sleeper", description: "A middle-aged wizard woken at night, indignant, thick with sleep, then careful" },
      tells: ["checks his palms for spell-light he cannot summon", "answers questions nobody asked"],
      knows: ["What the Bureau wanted from the ballad's audience: names of those who came to check their exposure.", "Nothing about the sponsor's wider objective; the director keeps it unresolved."],
      portrait: "/portraits/sleeper.svg",
    },
    {
      id: "visitor", name: "The Carriage Visitor", title: "A man in burgundy robes", faction: "unknown",
      summary: "Waiting inside the poster-covered carriage with a letter. 'You're difficult people to catch.' 'I think you're looking for my employer.' His employer's identity, the letter's contents and the destination are not disclosed by the film and must not be invented.",
      register: "Smooth, patient, faintly amused; a man who has never been hurried.", voice: { name: "Shadow Fell Visitor", description: "A smooth patient man, faintly amused, cultured, unhurried" },
      tells: ["his smile does not change when the room does", "keeps the letter exactly out of reach"],
      knows: ["That his employer wants the Wardens to come, and where; the letter carries the lead to the final town.", "He will not name the employer and the director must not."],
      portrait: "/portraits/visitor.svg",
    },
  ],
  roles: [
    { id: "soraya", label: "Soraya Anvar", summary: "Pure negotiation with the Armada behind you. Your risk is not a fight; it is the Congress." },
    { id: "navid", label: "Navid Qasran", summary: "Hire the deniables without saying what Halyra cannot afford to have repeated. Varya is reading you." },
    { id: "tav", label: "Tavian Larkvale", summary: "Make the ballad famous and let the exaggerations do their work. The room is reading you." },
    { id: "thorbin", label: "Thorbin Ironhart", summary: "Question a man who thinks you beneath notice. Get words Serena can swear to." },
    { id: "varya", label: "Varya Stormveil", summary: "Say little. Decide whether a lead is a lead or a leash." },
    { id: "serena", label: "Serena Duskbane", summary: "Take testimony yourself. Tyr takes no hearsay." },
  ],
  meters: [
    { id: "standing", label: "Standing", description: "How much they fear and respect you right now.", start: 55, axes: [{ axis: "command", weight: 1 }, { axis: "composure", weight: 0.5 }, { axis: "pressure", weight: 0.3 }] },
    { id: "rapport", label: "Rapport", description: "How willing they are to keep talking to you.", start: 30, axes: [{ axis: "warmth", weight: 1 }, { axis: "pressure", weight: -0.6 }, { axis: "candour", weight: 0.3 }] },
    { id: "evidence", label: "Evidence", description: "Usable words in their own mouth, within the right hearing. Serena's bar.", start: 10, axes: [{ axis: "candour", weight: 0.2 }], driftScale: 3 },
    { id: "cover", label: "Cover", description: "How intact your story is.", start: 70, axes: [{ axis: "composure", weight: 1 }, { axis: "candour", weight: 0.3 }, { axis: "pressure", weight: -0.4 }] },
    { id: "suspicion", label: "Suspicion", description: "How sure they are that you are not what you say.", start: 30, axes: [{ axis: "composure", weight: -1 }, { axis: "pressure", weight: 0.5 }, { axis: "warmth", weight: -0.2 }] },
    { id: "fame", label: "Fame", description: "How far the ballad will travel by morning.", start: 20, axes: [{ axis: "showmanship", weight: 1 }, { axis: "command", weight: 0.3 }] },
  ],
  acts: [
    {
      id: "palace",
      title: "Act I. The Shadow Falls",
      summary: "The Sky Palace, the week after the dinner. Two survivors in a room with no windows; a dossier that points too neatly at Omahnd; a Shadow sent north to hire deniable hands.",
      beats: [
        {
          id: "no-windows",
          title: "A room with no windows",
          stance: "reading",
          playerRole: "soraya",
          counterpart: "indigo",
          present: ["navid"],
          outsider: { mode: "mixed", confidence: "high", note: "A captured assassin with nothing left: threat and vulnerable at once. No Warden is in the room; Soraya reads him by her own lights." },
          location: "A windowless room in the Sky Palace; blue anchor-light in the walls; Navid at the door with the dispatch folio.",
          goal: "Get the Indigo to say, in his own words, who dressed the device in Halyra's blue, without handing the Congress another inquiry.",
          notes: "Soraya holds every card except time. Calm authority earns standing; warmth, oddly, earns more than threats because he expects threats. Sustained contempt or pressure makes him retreat into silence and makes Navid write something down for the Congress. She may not threaten restoration or severance; Halyran law forbids it and she knows it. The pig may be mentioned; the ballad never attributes that spell and neither does she. Never let him name the sponsor's objective; he does not know it and the story keeps it open.",
          opening: "Your father's cutlery has opinions, Caliphina. I have none left.",
          succeedWhen: "He says 'Bureau' or 'the Eminence', or admits the blue was a costume, unprompted, within Navid's hearing.",
          failWhen: "He goes silent for good, or Navid notes the methods for the Congress (rapport at zero or sustained contempt for three turns).",
          meters: ["standing", "rapport", "evidence"],
          maxTurns: 10,
        },
        {
          id: "your-deniables",
          title: "Your deniables",
          stance: "being-read",
          playerRole: "navid",
          counterpart: "varya",
          present: ["tav"],
          outsider: { mode: "authority", confidence: "medium", note: "An officer of the Sky Armada buying deniable hands: authority until his anxiety makes him something to doubt, or to protect." },
          location: "The back room of the AKA In; the Shahin moored behind; Tav pretending to tune a lute.",
          goal: "Hire the Stormwardens without saying more than Halyra can afford to have repeated.",
          notes: "Varya reads him. Anxiety in his voice and she presses on what he is not saying; contempt for the room and Tav's charm goes cold; composure and candour earn the commission. He must convey: twelve came, two talked, the ballad is the bait, Halyra needs evidence and warrants it can act upon, the hands must be deniable. He must not name Soraya as commissioner; if he does, his cover drops. Tav may name a price. Varya may say 'Close the door' to end it either way.",
          opening: "You came in a Shadow, Lieutenant. So the crown's attention has fallen on someone. Sit. Tell me who.",
          succeedWhen: "Varya accepts the job in her own words, or Tav names a price and she does not object.",
          failWhen: "Suspicion reaches 85: she concludes Halyra is setting them up as patsies and walks.",
          meters: ["cover", "suspicion", "rapport"],
          maxTurns: 8,
        },
      ],
    },
    {
      id: "tour",
      title: "Act II. Make It Famous",
      summary: "Six months on the road across Tharcia. Posters, screaming fans, a count at every stop, and the ones who talk.",
      beats: [
        {
          id: "make-it-famous",
          title: "Make it famous",
          stance: "being-read",
          playerRole: "tav",
          counterpart: "heckler",
          present: ["thorbin", "brask", "lyra"],
          outsider: { mode: "nuisance", confidence: "medium", note: "A heckler until he counts the room or his hands light, then a predator. A nuisance is not a combat encounter." },
          location: "A packed tavern, standing room only, the poster on the wall; Thorbin at the bar, Brask by the back passage, Lyra not drinking anything from in here.",
          goal: "Make the room love you and let the ballad's exaggerations do their work. Notice who reacts to the wrong details.",
          notes: "The player performs and banters; showmanship raises fame. The heckler baits him about the pork verse because he knows it is wrong about who cast it: reacting to that is his self-identification, and the director should let the tell show rather than say it. Anxiety in Tav's voice raises suspicion; the troupe must stay inconspicuous, which they are terrible at. If suspicion climbs past 85 the room turns and this becomes the run-out-of-town night. The heckler's hands may ignite if the ballad names the Bureau to his face.",
          opening: "Sing the pork verse again, minstrel. I want to hear who you say cast it.",
          succeedWhen: "Fame reaches 70, or the heckler reacts to a planted error in a way the room can see.",
          failWhen: "Suspicion reaches 85 and the room turns.",
          meters: ["fame", "suspicion"],
          maxTurns: 8,
          force: { threat: "The heckler's hands ignite violet and the room scatters.", requires: ["muscle", "concurrence"], scale: "scuffle" },
        },
        {
          id: "the-alley",
          title: "So who did do the planning, lad?",
          stance: "reading",
          playerRole: "thorbin",
          counterpart: "heckler",
          present: ["brask", "serena", "varya"],
          outsider: { mode: "predator", confidence: "high", note: "Held, not yet charged: the moment Serena takes custody, protecting him becomes real; the pressure is Brask's forearm, never words." },
          location: "The alley behind the tavern; Brask's forearm across the man's chest; a lit window above where Varya writes beside Serena.",
          goal: "Get an admission Serena can swear to. Tyr takes no hearsay, so the words must be his.",
          notes: "He talks down to a dwarf and does not look up until it is too late. Thorbin's warmth and patience open him more than pressure; Brask supplies the pressure without a word. Evidence moves only on usable admission in his own words within Serena's hearing; Varya's look asks 'Is that enough?' and Serena's head-shake means not yet. If he tries a word of power the scene tips; Lyra is not in the alley, so cover is short.",
          opening: "Do I know you, half-man?",
          succeedWhen: "He admits, in his own words, that he was sent to hear the ballad and count who came, or names the Bureau's interest in it.",
          failWhen: "Rapport reaches zero, or he is silenced by a fight that goes badly.",
          meters: ["standing", "rapport", "evidence"],
          maxTurns: 10,
          force: { threat: "He tries a word of power with Brask's forearm across his throat.", requires: ["muscle", "concurrence", "legitimacy"] },
        },
        {
          id: "stay-inconspicuous",
          title: "Stay inconspicuous",
          stance: "being-read",
          playerRole: "varya",
          counterpart: "watch-captain",
          present: ["tav", "brask"],
          outsider: { mode: "authority", confidence: "high", note: "A competent, brusque captain doing real work; never a predator. Cooperate, assess jurisdiction, manage face, ask for the concrete rule." },
          location: "The watch house of a Tharcian market town, the morning after the mob; the carriage impounded in the yard.",
          goal: "Get the troupe released with the carriage and no names written down.",
          notes: "The captain is Tharcian, not Rubrican; he wants the paperwork closed and the Magisterium out of his town. Varya says little; stillness reads as authority, anxiety reads as guilt. Tav's charm helps until it becomes performance. Brask's literal answers are dangerous and funny. If cudgels come out, the troupe has muscle and a face on hand.",
          opening: "A wizard of the Magisterium goes missing the night your troupe plays, and you would like your carriage back.",
          succeedWhen: "He releases the troupe and the carriage without recording names.",
          failWhen: "Suspicion reaches 85 and he sends for a magistrate.",
          meters: ["cover", "suspicion"],
          maxTurns: 8,
          force: { threat: "The captain's men reach for their cudgels.", requires: ["muscle", "face"], scale: "scuffle" },
        },
        {
          id: "morning",
          title: "Morning.",
          stance: "reading",
          playerRole: "serena",
          counterpart: "sleeper",
          present: ["kael", "lyra", "brask"],
          outsider: { mode: "mixed", confidence: "high", note: "A frightened hostile wizard: custody and evidence can coexist. Kael protects first; Serena leads nowhere." },
          location: "A snowy cottage bedroom in the middle of the night; Kael's hands over the wizard's; Lyra already in the corner; Brask on the stairs with a red blanket.",
          goal: "Take his testimony yourself. A paladin swears only to what her own ears heard, so lead nowhere; let him speak.",
          notes: "Serena must not put words in his mouth; if the director judges she led him, evidence does not move. Calm certainty earns standing; warmth earns rapport; pressure frightens him into noise that is not testimony. He knows what the Bureau wanted from the ballad's audience and nothing of the wider objective.",
          opening: "But it's the middle of the night.",
          succeedWhen: "He states, unprompted, what the Bureau wanted from the ballad's audience.",
          failWhen: "He is silenced by a fight that goes badly, or the director judges Serena led him three times.",
          meters: ["evidence", "rapport", "standing"],
          maxTurns: 8,
          force: { threat: "Blue spell-light gathers in his palms under Kael's hands.", requires: ["concurrence", "muscle"], scale: "scuffle" },
        },
        {
          id: "the-carriage",
          title: "You're difficult people to catch",
          stance: "reading",
          playerRole: "varya",
          counterpart: "visitor",
          present: ["tav", "brask", "serena"],
          outsider: { mode: "mixed", confidence: "low", note: "Unhurried, employer unnamed: read him on behaviour alone and reclassify on evidence. The letter, not the man, is the object." },
          location: "A wet town square; the poster-covered carriage; a man in burgundy robes inside it with a letter.",
          goal: "Decide whether the letter is a lead or a leash, and take it on your terms.",
          notes: "The visitor is never hurried and never names his employer; the director must not either. Varya's stillness earns standing; curiosity earns the letter; pressure amuses him. The beat resolves on 'Close the door': the letter carries the lead to the final town, whose name stays unspoken.",
          opening: "You're difficult people to catch.",
          succeedWhen: "Varya secures the letter and its terms without the employer being named.",
          failWhen: "Rapport reaches zero and he leaves with the letter, or a fight goes badly.",
          meters: ["standing", "rapport", "evidence"],
          maxTurns: 8,
          force: { threat: "The visitor's smile does not change as his hand finds something under the paper.", requires: ["blade", "brains", "stealth"] },
        },
      ],
    },
  ],
  clips: [
    ...reactions("indigo", "a bound Murex Bureau assassin in a grounded cell, black robes torn, violet embers dead in his eyes", "windowless stone room lit by blue anchor-light"),
    ...reactions("varya", "Varya Stormveil, dark practical clothing, a ledger open under her hand", "the low back room of a tavern by lamplight"),
    ...reactions("heckler", "a young red-robed Magisterium functionary, sneer fading", "a packed tavern, then a wet alley at night"),
    ...reactions("watch-captain", "a weary provincial watch captain behind a desk", "a stone watch house at grey morning"),
    ...reactions("sleeper", "a middle-aged wizard in a nightshirt, pinned hands, snow at the window", "a snowy cottage bedroom by candlelight"),
    ...reactions("visitor", "a smooth man in burgundy robes seated inside a carriage, a sealed letter in his hand", "the inside of a poster-covered carriage in rain"),
    establishing("sky-palace-cell", "Establishing shot, a windowless room in a sky palace, blue anchor-lights set into pale stone walls, a bound figure at the far wall, gold light from a doorway. Photoreal, slow push-in, 6 seconds."),
    establishing("aka-in-back-room", "Establishing shot, the back room of a tavern by lamplight, a Sayah-class sky cutter's hull visible through a rear window, a lute on the table. Photoreal, slow push-in, 6 seconds."),
    establishing("packed-tavern", "Establishing shot, a standing-room-only tavern, a bard on a dais, a poster on the wall, a red-robed man at the back. Photoreal, slow dolly, 6 seconds."),
    establishing("the-alley", "Establishing shot, a wet alley behind a tavern at night, a huge man holding a red-robed wizard to the wall, a lit window above. Photoreal, static, 6 seconds."),
    establishing("watch-house", "Establishing shot, a provincial watch house at grey morning, an impounded carriage in the yard beyond the window. Photoreal, slow pan, 6 seconds."),
    establishing("snowy-cottage", "Establishing shot, a snowy cottage at night, one candle in an upstairs window, footprints to the door. Photoreal, slow push-in, 6 seconds."),
    establishing("wet-square-carriage", "Establishing shot, a wet town square at dusk, a poster-covered carriage, a door opening onto a seated figure. Photoreal, slow dolly, 6 seconds."),
  ],
  prohibitions: [
    "Varya, never Veyra, Verya or Varia. Piss and Moan, never Piss and Vinegar. Serena is not Lord Marshal. Ogma not Oghma. Concurrence not Weave. Morrighad not Moradin. The Cadence, not Harpers. Tharcia and the Rubrican Magisterium, never Thay or Red Wizards. AKA In is the spelling.",
    "SEALED: never reconstruct, infer or invent Thorbin's third loss at Mhasun; in text it is a failure to pick up a stone in time, carried unstoned, and the narrator is never told.",
    "SEALED: never identify or hint at the source of Kael's power; the Stormwardens do not know it.",
    "SEALED: never explain the source, purpose or destination of Laleh's call north; she does not know why.",
    "OPEN: never name the assassins' sponsor's objective beyond attacking the dynasty, the surviving assassins' identities, the carriage visitor's employer, or the final town.",
    "The ballad never attributes the pig polymorph. Soraya commissioned the Stormwardens; the deniables never say so aloud in Act II.",
    "Never escalate a palace beat into violence. Never let Soraya threaten restoration or severance.",
  ],
};

export const shadowFell = defineWorld(pack);
